version: "2"
services:
  web:
    build: .
    volumes:
      - ./nodejs:/usr/src/app/
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
